[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

# Redirect all requests to index.html (for SPAs, optional)
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com;
      style-src 'self' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com;
      img-src 'self' data:;
      font-src 'self' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com data:;
      connect-src 'self' https://api.openai.com https://openrouter.ai https://*.openrouter.ai http://localhost:1234 http://127.0.0.1:1234;
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self'
    """
